[project]
title      = "Spotify Pop Analytics"
version    = "0.1.0"
port       = 8501
slug       = "spotify-pop-analytics"
entrypoint = "hello.py"

[branding]
name         = "Spotify Pop Analytics"
logo         = "images/logo.png"
favicon      = "images/favicon.ico"
primaryColor = "#1DB954"

[data.sample_csv]
type = "csv"
path = "data/sample.csv"

[logging]
level  = "INFO"
format = "%(asctime)s - %(levelname)s - %(message)s"
